version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - "Type: Chore"
  ignore:
  - dependency-name: typescript
    versions:
    - 4.0.5
    - 4.1.5
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.24.2
  - dependency-name: tsdx
    versions:
    - 0.13.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: stylelint
    versions:
    - 13.3.2
