# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:

  # A short description of the repository that will show up on GitHub
  description: A collection of brutally simple components for building administrative dashboards with React Bootstrap.

  # Either 'true' to enable issues for this repository, 'false' to disable them.
  has_issues: true

  # Either 'true' to enable projects for this repository, or 'false' to disable them.
  # If projects are disabled for the organization, passing 'true' will cause an API error.
  has_projects: false

  # Either 'true' to enable the wiki for this repository, 'false' to disable it.
  has_wiki: false

  # Either 'true' to enable downloads for this repository, 'false' to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either 'true' to allow squash-merging pull requests, or 'false' to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either 'true' to allow merging pull requests with a merge commit, or 'false'
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either 'true' to allow rebase-merging pull requests, or 'false' to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either 'true' to allow squash-merging pull requests, or 'false' to prevent squash-merging.
  # Commented out for now (see https://github.com/probot/settings/issues/134)
#  delete_branch_on_merge: true

# https://developer.github.com/v3/repos/branches/#update-branch-protection
branches:
  - name: master
    protection:
      required_linear_history: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: [ spartan-ui-bot ]
          teams: [ community, endemolshinegroup ]
      required_status_checks:
        strict: true
        contexts: [
          lint,
          test,
          codecov/project,
        ]
      enforce_admins: false
      restrictions:
        users: [ spartan-ui-bot ]
        teams: [ community, endemolshinegroup ]

labels:

  - name: "duplicate"
    color: "ededed"
    description: "This issue or Pull Request already exists"

  - name: "help wanted"
    color: "e99695"
    description: "Extra attention is needed"

  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"

  - name: "Priority: Critical"
    color: "ee0701"

  - name: "Priority: High"
    color: "d93f0b"

  - name: "Priority: Medium"
    color: "fbca04"

  - name: "Priority: Low"
    color: "0e8a16"

  - name: "Status: Abandoned"
    color: "000000"
    description: "The issue or Pull Request is wontfix"

  - name: "Status: Blocked"
    color: "ee0701"
    description: "Progress on the issue is Blocked"

  - name: "Status: In Progress"
    color: "cccccc"
    description: "Work in Progress"

  - name: "Status: Proposal"
    color: "d4c5f9"
    description: "Request for comments"

  - name: "Status: PR Welcome"
    color: "2E7733"
    description: "Welcome to Pull Request"

  - name: "Status: Review Needed"
    color: "fbca04"
    description: "Request for review comments"

  - name: "Status: Need More Info"
    color: "F9C90A"
    description: "Lacks enough info to make progress"

  - name: "Type: Breaking Change"
    color: "b60205"
    description: "Includes breaking changes"

  - name: "Type: Bug"
    color: "ee0701"
    description: "Bug or Bug fixes"

  - name: "Type: Documentation"
    color: "5319e7"
    description: "Documentation only changes"

  - name: "Type: Feature"
    color: "1d76db"
    description: "New Feature"

  - name: "Type: Refactoring"
    color: "fbca04"
    description: "A code change that neither fixes a bug nor adds a feature"

  - name: "Type: Testing"
    color: "257759"
    description: "Adding missing tests or correcting existing tests"

  - name: "Type: Chore"
    color: "abd406"
    description: "Repository Maintenance"

  - name: "Type: CI"
    color: "ffd412"
    description: "Changes to CI configuration files and scripts"

  - name: "Type: Research"
    color: "ff613d"
    description: "Further research is requested"

  - name: "Type: Question"
    color: "cc317c"
    description: "Further information is requested"

  - name: "Package: Icons"
    color: "973ddb"
    description: "Icons package"

  - name: "Package: Layout"
    color: "973ddb"
    description: "Layout package"

  - name: "Package: Nav"
    color: "973ddb"
    description: "Nav package"

  - name: "Package: Select"
    color: "973ddb"
    description: "Select package"

  - name: "Package: Datepicker"
      color: "973ddb"
      description: "Datepicker package"
